### PR TITLE
Misjudged on retained cycle

### PR DESCRIPTION
**Pull request by without2002**
Hi Gricha, thank you for your reply. I have added the code to filter result of cycle detector. Please check it.
PS: I'm sorry for that I posted the issue to FBMemoryProfiler repo, but I think the code should in FBRetainCycleDetector project. So I can't link the issue. The link of issue is here: https://github.com/facebook/FBMemoryProfiler/issues/35

### CODE REVIEW

**Comment by without2002** [comment]
@Gricha Firstly, I'm sorry for @ you. I want to pull request, but the checks alway fail. I checked the reason of fail. That's about simulator SDK, I have not changed any thing about the project. I don't know how to fix it too. Could you give me some suggestions?

**Comment by Gricha** [comment]
@without2002 Sorry for radio silence. I've started fixing Travis integration. Once that's done we can get deep into the PR. Thanks!

**Comment by Megra** [comment]
Hi @without2002, do you still want this checked in and pulled?
Try rebasing the change to kick off the Travis CL again, it should be working now.

**Comment by Megra** [comment]
I opened https://github.com/facebook/FBRetainCycleDetector/pull/49 to improve some of the operations for speed. I doubt @without2002 is still interested in pushing this after over a year of waiting but the credit is definitely his.

**Pull request closed without merging**
